methods:
- method_kwargs: null
  model_cls: GBM
  model_hyperparameters:
    ag_args:
      name_suffix: _c1
    ag_args_ensemble:
      model_random_seed: 0
      vary_seed_across_folds: false
  name: LightGBM_c1_BAG_L1
  num_bag_folds: 8
  num_bag_sets: 1
  time_limit: 3600
  type: AGModelBagExperiment
- method_kwargs: null
  model_cls: GBM
  model_hyperparameters:
    ag_args:
      name_suffix: _r1
    ag_args_ensemble:
      model_random_seed: 0
      vary_seed_across_folds: false
    bagging_fraction: 0.7574558351137
    bagging_freq: 1
    cat_l2: 0.0256019070484
    cat_smooth: 0.0615299199096
    extra_trees: true
    feature_fraction: 0.4132863481618
    lambda_l1: 0.9871405883296
    lambda_l2: 1.581265142979
    learning_rate: 0.0056459206537
    max_cat_to_onehot: 63
    min_data_in_leaf: 48
    min_data_per_group: 10
    num_leaves: 4
  name: LightGBM_r1_BAG_L1
  num_bag_folds: 8
  num_bag_sets: 1
  time_limit: 3600
  type: AGModelBagExperiment
